import type { ThemePack } from '../../engine/theme.ts'

export const spaceStation: ThemePack = {
  id: 'space-station',
  name: 'Kepler-9 Relay Station',

  // "Escape Pod" is kept back for the finale (stage 4).
  systemNames: [
    'Life Support',
    'Airlock Seal',
    'Reactor Core',
    'Nav Array',
    'Comms Relay',
    'Hydroponics Bay',
    'Cryo Bay',
    'Med Bay',
    'Cargo Hold',
    'Gravity Ring',
    'Thermal Shield',
    'Water Reclaimer',
    'Docking Clamp',
    'Power Grid',
  ],

  words: [
    'BOLT',
    'CRYO',
    'DOCK',
    'FUEL',
    'HULL',
    'MOON',
    'STAR',
    'WIRE',
    'CABIN',
    'CARGO',
    'COMET',
    'HATCH',
    'LASER',
    'ORBIT',
    'PROBE',
    'RADAR',
    'RADIO',
    'ROVER',
    'SOLAR',
    'VALVE',
    'VISOR',
    'BEACON',
    'COSMOS',
    'ENGINE',
    'GALAXY',
    'HELMET',
    'LAUNCH',
    'MAGNET',
    'MODULE',
    'NEBULA',
    'OXYGEN',
    'PLANET',
    'PLASMA',
    'PULSAR',
    'ROCKET',
    'SENSOR',
    'SIGNAL',
    'TETHER',
    'VACUUM',
    'WRENCH',
    'ZENITH',
    'AIRLOCK',
    'ANTENNA',
    'BATTERY',
    'CAPSULE',
    'CIRCUIT',
    'COMPASS',
    'CONSOLE',
    'COOLANT',
    'DOCKING',
    'ECLIPSE',
    'GRAVITY',
    'REACTOR',
    'STATION',
    'ASTEROID',
    'MOONBASE',
    'STARSHIP',
    'THRUSTER',
    'SATELLITE',
    'SPACESUIT',
    'TELESCOPE',
  ],

  riddles: [
    {
      question:
        "I have keys but open no locks. I have space but no room. You can enter, but you can't go inside. What am I?",
      answer: 'keyboard',
      hints: ["You've probably touched one today.", 'It sits in front of a screen.'],
    },
    {
      question: 'The more you take, the more you leave behind. What are they?',
      answer: 'footsteps',
      altAnswers: ['steps', 'footprints'],
      hints: ['Think about walking.', 'Astronauts left theirs on the Moon.'],
    },
    {
      question: 'I have a face and two hands, but no arms or legs. What am I?',
      answer: 'clock',
      altAnswers: ['watch'],
      hints: ["You check me when you're running late.", 'I tick.'],
    },
    {
      question:
        'I have cities but no houses, forests but no trees, and water but no fish. What am I?',
      answer: 'map',
      altAnswers: ['atlas'],
      hints: ['Navigators rely on me.', "I'm usually folded up or on a screen."],
    },
    {
      question:
        'I speak without a mouth and hear without ears. I have no body, but I come alive in empty halls. What am I?',
      answer: 'echo',
      hints: ['Shout into a canyon.', 'I repeat whatever you say.'],
    },
    {
      question: 'What gets wetter the more it dries?',
      answer: 'towel',
      hints: [
        "You'd reach for me after a shower.",
        'Every good space traveller knows where theirs is.',
      ],
    },
    {
      question: 'The more of me there is, the less you can see. What am I?',
      answer: 'darkness',
      altAnswers: ['dark'],
      hints: ['Space is full of me.', 'Turn off the lights.'],
    },
    {
      question: 'What goes up but never comes down?',
      answer: 'age',
      altAnswers: ['your age'],
      hints: ['It happens on every birthday.', "Everyone has one, and it's always growing."],
    },
    {
      question: 'What can you catch but never throw?',
      answer: 'cold',
      altAnswers: ['common cold', 'breath'],
      hints: ['You might start sneezing.', "It's going around the crew quarters."],
    },
    {
      question: 'What has to be broken before you can use it?',
      answer: 'egg',
      altAnswers: ['eggs'],
      hints: ['Think breakfast.', 'It comes in a shell.'],
    },
    {
      question: 'What belongs to you, but other people use it more than you do?',
      answer: 'name',
      altAnswers: ['your name'],
      hints: ['People call you by it.', "It's printed on your crew badge."],
    },
    {
      question: 'What has a neck but no head?',
      answer: 'bottle',
      hints: ['You drink from me.', 'Sometimes I carry a message across the sea.'],
    },
    {
      question: "What has one eye but can't see?",
      answer: 'needle',
      hints: ["It's used for sewing.", 'Thread goes through its eye.'],
    },
    {
      question: "I'm always coming, but I never arrive. What am I?",
      answer: 'tomorrow',
      hints: ['Think about time.', "When today ends, I'm still one day away."],
    },
    {
      question: 'What breaks as soon as you say its name?',
      answer: 'silence',
      hints: ["It's what this station has been for three hours.", 'Shh.'],
    },
  ],

  flavor: {
    caesar: [
      'Intercepted transmission',
      'Corrupted crew message',
      'Encrypted door log',
      'Garbled distress signal',
    ],
    sequence: [
      'Reactor pressure readings',
      'Oxygen levels, logged hourly',
      'Hull temperature samples',
      'Power grid output',
    ],
    anagram: [
      'Corrupted file name in the crew log',
      'Scrambled access keyword',
      'Damaged cargo label',
      'Jumbled system alert',
    ],
    riddle: ['HALCYON voice lock', "Commander's security question", 'Personal locker prompt'],
  },
}
